// ============================================================
// APP VERSION
// ============================================================
const APP_VERSION = '1.2.260421.2225';

// ============================================================
// DATA - 28 SZCZYTÓW KGP
// ============================================================
const PEAKS = [
  { id:1, name:"Rysy", height:2499, range:"Tatry", difficulty:5, lat:49.179576, lon:20.088108, season:[7,8,9], terrain:"alpine",
    routes:[
      {name:"Polska (Palenica Białczańska)", parking:{name:"Palenica Białczańska",lat:49.2559428,lon:20.1030717,note:"Rezerwacja obowiązkowa (tpn.gov.pl), 35-75 zł, ~1200 miejsc. W sezonie przed 6:00"}, station:{name:"Zakopane PKP", info:"Bus do Palenicy ~40 min"}, trail:{dist:22.5, up:210, down:150, ascent:1200}},
      {name:"Słowacja (Štrbské Pleso)", parking:{name:"Štrbské Pleso",lat:49.1247003,lon:20.0746944,note:"~500 miejsc, ~15 EUR/dzień, asfalt. Bez rezerwacji. Wcześnie rano w sezonie"}, station:{name:"Štrba PKP", info:"Kolej zębata do Štrbské Pleso ~15 min"}, trail:{dist:14, up:180, down:130, ascent:1000}}
    ],
    stamps:[{name:"Schronisko Morskie Oko",type:"🏠",note:"~1h 45min zejścia"},{name:"Chata Pod Rysami",type:"🏚️",note:"15 min poniżej szczytu"}],
    photo:"Przy słupku granicznym PL/SK - tablica za Tobą" },
  { id:2, name:"Babia Góra", height:1725, range:"Beskid Żywiecki", difficulty:4, lat:49.573023, lon:19.529330, season:[6,7,8,9], terrain:"alpine",
    parking:[{name:"Przełęcz Krowiarki",lat:49.5786,lon:19.5692,note:"~100 miejsc, 20 zł/dzień, szuter. W sezonie zajęty przed 6:00"}],
    station:{name:"Sucha Beskidzka PKP", info:"Bus do Zawoi ~40 min"},
    trail:{dist:11, up:120, down:100, ascent:720},
    stamps:[{name:"Schronisko Markowe Szczawiny",type:"🏠",note:"Na szlaku w górę"},{name:"Kasa BPN Zawoja",type:"🎫",note:"Przy wejściu do parku"}],
    photo:"Na szczycie przy tablicy z napisem Babia Góra 1725 m" },
  { id:3, name:"Śnieżka", height:1603, range:"Karkonosze", difficulty:2, lat:50.736021, lon:15.739599, season:[5,6,7,8,9,10], terrain:"exposed",
    parking:[{name:"Karpacz - dolna stacja wyciągu",lat:50.7819382,lon:15.7230162,note:"~300 miejsc, 30-50 zł/dzień, asfalt. W sezonie przyjedź przed 8:00"}],
    station:{name:"Jelenia Góra PKP", info:"Bus do Karpacza ~40 min"},
    trail:{dist:14, up:160, down:140, ascent:880},
    stamps:[{name:"Dom Śląski - schronisko",type:"🏠",note:"Na samym szczycie"},{name:"Strzecha Akademicka",type:"🏠",note:"Na szlaku"}],
    photo:"Przy obserwatorium meteorologicznym - okrągły budynek" },
  { id:4, name:"Śnieżnik", height:1423, range:"Masyw Śnieżnika", difficulty:3, lat:50.207500, lon:16.847558, season:[5,6,7,8,9,10], terrain:"forest",
    parking:[{name:"Międzygórze",lat:50.2292,lon:16.7658,note:"~150 miejsc, darmowy, utwardzony. Przy wjeździe do wsi"}],
    station:{name:"Bystrzyca Kłodzka PKP", info:"Bus do Międzygórza ~30 min"},
    trail:{dist:16, up:180, down:160, ascent:850},
    stamps:[{name:"Schronisko PTTK Na Śnieżniku",type:"🏠",note:"Pieczątka przeniesiona ze szczytu do schroniska"}],
    photo:"Przy wieży widokowej na szczycie (stalowo-szklana, 34m, z 2022 r.)" },
  { id:5, name:"Tarnica", height:1346, range:"Bieszczady", difficulty:3, lat:49.074770, lon:22.726323, season:[6,7,8,9], terrain:"exposed",
    routes:[
      {name:"Wołosate", parking:{name:"Wołosate",lat:49.0592,lon:22.6878,note:"~200 miejsc, 25 zł/dzień, szuter. Limit miejsc! Przed 8:00 w sezonie"}, station:{name:"Sanok PKP", info:"Bus do Ustrzyk Górnych ~2h"}, trail:{dist:10, up:110, down:100, ascent:600}},
      {name:"Muczne (via Przełęcz Bukowska)", parking:{name:"Muczne",lat:49.0678,lon:22.7303,note:"~50 miejsc, darmowy, szuter. Alternatywa dla Wołosatego"}, station:{name:"Sanok PKP", info:"Bus do Ustrzyk Górnych ~2h"}, trail:{dist:14, up:140, down:130, ascent:650}}
    ],
    stamps:[{name:"Punkt kasowy w Wołosatem",type:"🎫",note:"Przy starcie szlaku"},{name:"Schronisko Kremenaros",type:"🏠",note:"Ustrzyki Górne"}],
    photo:"Na szczycie z widokiem na Połoniny - brak drzew, pełna panorama" },
  { id:6, name:"Turbacz", height:1310, range:"Gorce", difficulty:2, lat:49.542824, lon:20.111384, season:[5,6,7,8,9,10], terrain:"forest",
    parking:[{name:"Koninki - Polana Oberówka",lat:49.5617,lon:20.1467,note:"~100 miejsc, darmowy, szuter. Dobry punkt startowy na Turbacz"}],
    station:{name:"Rabka-Zdrój PKP", info:"Szlak z Rabki ~3h"},
    trail:{dist:12, up:130, down:120, ascent:650},
    stamps:[{name:"Schronisko PTTK im. Orkana",type:"🏠",note:"Przy szczycie, 10 min zejścia"}],
    photo:"Przy tablicy szczytu z widokiem na Tatry w tle" },
  { id:7, name:"Radziejowa", height:1266, range:"Beskid Sądecki", difficulty:2, lat:49.449304, lon:20.604122, season:[5,6,7,8,9,10], terrain:"forest",
    parking:[{name:"Piwniczna-Zdrój",lat:49.4381,lon:20.7167,note:"~30 miejsc, darmowy, utwardzony. Przy starcie szlaku"}],
    station:{name:"Piwniczna-Zdrój PKP", info:"Szlak ze stacji ~3h"},
    trail:{dist:13, up:140, down:130, ascent:700},
    stamps:[{name:"Pieczątka na szczycie",type:"📬",note:"Skrzynka przy tablicy"},{name:"Schronisko na Przehybie",type:"🏠",note:"Na szlaku"}],
    photo:"Przy drewnianym słupku szczytowym z tablicą 1262 m" },
  { id:8, name:"Skrzyczne", height:1257, range:"Beskid Śląski", difficulty:2, lat:49.684574, lon:19.030274, season:[5,6,7,8,9,10], terrain:"forest",
    parking:[{name:"Szczyrk - ul. Myśliwska",lat:49.6792,lon:19.0308,note:"~150 miejsc, 20-30 zł/dzień, asfalt. Przy dolnej stacji wyciągu"},{name:"Przełęcz Przegibek",lat:49.7922778,lon:19.1290319,note:"ok. 36 miejsc, darmowy, kamienie, dobry start na Skrzyczne"}],
    station:{name:"Bielsko-Biała PKP", info:"Bus do Szczyrku ~45 min"},
    trail:{dist:9, up:100, down:90, ascent:600},
    stamps:[{name:"Schronisko na Skrzycznem",type:"🏠",note:"Na szczycie"}],
    photo:"Przy maszcie telekomunikacyjnym i tablicy szczytowej" },
  { id:9, name:"Mogielica", height:1171, range:"Beskid Wyspowy", difficulty:2, lat:49.655320, lon:20.276674, season:[4,5,6,7,8,9,10,11], terrain:"forest",
    parking:[{name:"Jurków",lat:49.6650,lon:20.2617,note:"~30 miejsc, darmowy, szuter. Przy karczmie Baranówka"}],
    station:{name:"Mszana Dolna PKP", info:"Bus przez Jurków, kilka kursów dziennie ~30 min"},
    trail:{dist:8, up:90, down:85, ascent:520},
    stamps:[{name:"Karczma Baranówka",type:"🍺",note:"W Jurkowie, przy starcie"},{name:"Pieczątka na szczycie",type:"📬",note:"Skrzynka - może zniszczona"}],
    photo:"Przy wieży widokowej na szczycie (stalowa, 23m, z 2022 r.) lub przy tablicy szczytowej" },
  { id:10, name:"Lackowa", height:997, range:"Beskid Niski", difficulty:3, lat:49.426547, lon:21.102479, season:[5,6,7,8,9,10], terrain:"forest",
    parking:[{name:"Czarne",lat:49.4133,lon:21.0700,note:"~15 miejsc, darmowy, szuter. Przy szkole, najkrótszy szlak na Lackową"}],
    station:{name:"Krynica PKP", info:"Bus do Czarnego ~1h"},
    trail:{dist:10, up:110, down:105, ascent:550},
    stamps:[{name:"Pieczątka na szczycie",type:"📬",note:"Skrzynka przy tablicy"}],
    photo:"Na szczycie przy tablicy - uwaga na nagłe mgły!" },
  { id:11, name:"Wysoka", height:1050, range:"Pieniny", difficulty:2, lat:49.380253, lon:20.555484, season:[4,5,6,7,8,9,10], terrain:"forest",
    parking:[{name:"Jaworki",lat:49.4060064,lon:20.5488490,note:"~100 miejsc, 15-20 zł/dzień, szuter. Przy wejściu do Wąwozu Homole"}],
    station:{name:"Szczawnica PKS", info:"Bus z Krakowa lub Nowego Targu"},
    trail:{dist:8, up:95, down:90, ascent:480},
    stamps:[{name:"Pieczątka na szczycie",type:"📬",note:"Skrzynka na wierzchołku"}],
    photo:"Na szczycie z widokiem na dolinę Dunajca" },
  { id:12, name:"Szczeliniec Wielki", height:919, range:"Góry Stołowe", difficulty:1, lat:50.484814, lon:16.341006, season:[4,5,6,7,8,9,10,11], terrain:"forest",
    parking:[{name:"Karłów - Dworek",lat:50.4833,lon:16.3408,note:"~50 miejsc, 10 zł/5h, szuter. Najtańszy parking, krótki spacer do szlaku"},{name:"Karłów - główny",lat:50.4862052,lon:16.3352104,note:"~150 miejsc, 20 zł/dzień, asfalt. Najbliżej wejścia na szlak. W sezonie przed 9:00"}],
    station:{name:"Radków PKP", info:"Koleje Dolnośląskie, spacer 35 min"},
    trail:{dist:1.6, up:45, down:35, ascent:153},
    stamps:[{name:"Schronisko na Szczelińcu",type:"🏠",note:"Na płaskowyżu, bilet wstępu"}],
    photo:"Na skałkach z widokiem na Dolinę Kłodzką - efektowna ekspozycja" },
  { id:13, name:"Wysoka Kopa", height:1126, range:"Góry Izerskie", difficulty:2, lat:50.854716, lon:15.420915, season:[4,5,6,7,8,9,10,11], terrain:"forest",
    parking:[{name:"Orle",lat:50.8655,lon:15.4464,note:"~20 miejsc, darmowy, szuter. Najbliższy do szlaku na Wysoką Kopę"},{name:"Rozdroże Izerskie",lat:50.8597,lon:15.3981,note:"~50 miejsc, darmowy, szuter. Pojemny, dalej od szlaku"}],
    station:{name:"Szklarska Poręba Górna PKP", info:"Polregio / Koleje Dolnośląskie, szlak czerwonym GSS ~3h"},
    trail:{dist:12, up:130, down:120, ascent:480},
    stamps:[
      {name:"Skrzynka KGP na szlaku czerwonym (GSS)",type:"📬",lat:50.8547,lon:15.4209,note:"⚠️ Szczyt zamknięty od 2021 (ochrona cietrzewia)! Skrzynka ~300-400m od schroniska w kierunku Świeradowa"}
    ],
    photo:"⚠️ NIE na szczycie! Zdjęcie rób przy rogaczu z tablicą KGP na czerwonym szlaku GSS - ~400m za wiatą. Szczyt jest wyłączony z ruchu (ochrona cietrzewia)" },
  { id:14, name:"Skopiec", height:724, range:"Góry Kaczawskie", difficulty:1, lat:50.943927, lon:15.884706, season:[3,4,5,6,7,8,9,10,11,12], terrain:"forest",
    parking:[{name:"Komarno - Przełęcz Komarnicka",lat:50.9398486,lon:15.8777903,note:"~10 miejsc, darmowy, przy drodze na łąki. 860m do szczytu, 88m przewyższenia. Gdy pada - błoto!"}],
    station:{name:"Jelenia Góra PKP", info:"Bus miejski nr 2 do Komarnego, kilka kursów dziennie"},
    trail:{dist:5, up:45, down:40, ascent:280},
    stamps:[{name:"Pieczątka na szczycie",type:"📬",note:"Skrzynka - szybkie wejście"}],
    photo:"Przy żółtej tabliczce szczytowej i kamiennym kopcu (brak wieży!)" },
  { id:15, name:"Skalnik", height:945, range:"Rudawy Janowickie", difficulty:2, lat:50.808481, lon:15.900060, season:[4,5,6,7,8,9,10,11], terrain:"forest",
    parking:[{name:"Czarnów",lat:50.8012644,lon:15.9093058,note:"8 miejsc, darmowy, trudno o miejsca w sezonie. 2.2km do szczytu, 210m przewyższenia"},{name:"Gruszków - Przełęcz pod Średnicą",lat:50.8146083,lon:15.8620644,note:"~20 miejsc, darmowy, na Głównym Szlaku Sudeckim. 4.1km do szczytu, 343m przewyższenia"}],
    station:{name:"Kamienna Góra PKP", info:"Koleje Dolnośląskie, bus PKS do Czarnowa ~20 min"},
    trail:{dist:8, up:90, down:85, ascent:450},
    stamps:[{name:"Skrzynka na szczycie",type:"📬",note:"Czerwona skrzynka kilkanaście metrów od tabliczki (od 2024)"}],
    photo:"Przy tabliczce szczytowej na szczycie Skalnika (945m), nie na Ostrej Małej!" },
  { id:16, name:"Chełmiec", height:850, range:"Góry Wałbrzyskie", difficulty:1, lat:50.779549, lon:16.210974, season:[3,4,5,6,7,8,9,10,11,12], terrain:"forest",
    parking:[{name:"Boguszów-Gorce",lat:50.7603,lon:16.2025,note:"~30 miejsc, darmowy, asfalt. Ul. Kusocińskiego, przy szlaku zielonym"}],
    station:{name:"Wałbrzych PKP", info:"Bus ~20 min"},
    trail:{dist:5, up:50, down:45, ascent:280},
    stamps:[{name:"Wieża widokowa na szczycie",type:"📬",note:"Skrzynka zewnętrzna przy schodach (dostępna gdy wieża zamknięta)"}],
    photo:"Na wieży widokowej lub przy tablicy szczytowej" },
  { id:17, name:"Waligóra", height:936, range:"Góry Kamienne", difficulty:1, lat:50.680825, lon:16.278088, season:[3,4,5,6,7,8,9,10,11,12], terrain:"forest",
    parking:[{name:"Schronisko Andrzejówka",lat:50.6739,lon:16.2650,note:"~40 miejsc, darmowy, szuter. Przy schronisku Andrzejówka"}],
    station:{name:"Wałbrzych PKP", info:"Bus do Andrzejówki ~45 min"},
    trail:{dist:4, up:35, down:30, ascent:180},
    stamps:[{name:"Schronisko Andrzejówka",type:"🏠",note:"Przy parkingu - najpierw pieczątka!"}],
    photo:"Na szczycie przy tablicy - szybkie wejście ~20 min od schroniska" },
  { id:18, name:"Wielka Sowa", height:1015, range:"Góry Sowie", difficulty:2, lat:50.680278, lon:16.485556, season:[3,4,5,6,7,8,9,10,11,12], terrain:"forest",
    parking:[{name:"Rzeczka - Przełęcz Walimska",lat:50.6683,lon:16.4422,note:"~50 miejsc, 10-15 zł/dzień, szuter. Najbliższy parking, szlak ~1.5h"},{name:"Ludwikowice Kłodzkie",lat:50.6217,lon:16.4892,note:"~30 miejsc, darmowy, szuter. Dłuższa trasa ~3h, spokojniejsza alternatywa"}],
    station:{name:"Głuszyca Górna PKP", info:"Koleje Dolnośląskie, szlak ~3h"},
    trail:{dist:9, up:100, down:95, ascent:500},
    stamps:[{name:"Skrzynka na szczycie",type:"📬",note:"Niebieska skrzynka na rzeźbie sowy - zawsze dostępna"},{name:"Schronisko Sowa Sokolec",type:"🏠",note:"Weekendy 11-17"},{name:"Schronisko Zygmuntówka",type:"🏠",note:"Jugów"}],
    photo:"Przy wieży widokowej na szczycie" },
  { id:19, name:"Kłodzka Góra", height:765, range:"Góry Bardzkie", difficulty:1, lat:50.451670, lon:16.753222, season:[3,4,5,6,7,8,9,10,11,12], terrain:"forest",
    parking:[{name:"Bardo",lat:50.5069,lon:16.7400,note:"~50 miejsc, darmowy, asfalt. W centrum Barda, stąd szlak na Kłodzką Górę"}],
    station:{name:"Bardo Śląskie PKP", info:"Szlak ze stacji ~1h"},
    trail:{dist:6, up:55, down:50, ascent:320},
    stamps:[{name:"Pieczątka na szczycie",type:"📬",note:"Skrzynka przy tablicy"}],
    photo:"Przy wieży widokowej (stalowa, 35m, z 2020 r.) lub przy tablicy szczytowej" },
  { id:20, name:"Jagodna", height:977, range:"Góry Bystrzyckie", difficulty:2, lat:50.252457, lon:16.564419, season:[4,5,6,7,8,9,10,11], terrain:"forest",
    parking:[{name:"Schronisko Jagodna",lat:50.2528,lon:16.5417,note:"~30 miejsc, darmowy, szuter. Przy schronisku - zajmij przed 8:00 w sezonie"}],
    station:{name:"Bystrzyca Kłodzka PKP", info:"Bus do Jagodnej ~45 min"},
    trail:{dist:4, up:40, down:35, ascent:200},
    stamps:[{name:"Skrzynka pod wiatą na szczycie",type:"📬",note:"Od 2026, zawsze dostępna"},{name:"Schronisko PTTK Jagodna",type:"🏠",note:"Na Przełęczy Spalonej"}],
    photo:"Przy wieży widokowej (stalowa, 23m, z 2019 r.) lub przy tabliczce szczytowej" },
  { id:21, name:"Orlica", height:1084, range:"Góry Orlickie", difficulty:2, lat:50.353251, lon:16.360628, season:[4,5,6,7,8,9,10,11], terrain:"exposed",
    parking:[{name:"Zieleniec",lat:50.3536,lon:16.3917,note:"~100 miejsc, 15-20 zł/dzień, asfalt. Przy wyciągu narciarskim"}],
    station:{name:"Duszniki-Zdrój PKP", info:"Bus do Zieleńca ~20 min"},
    trail:{dist:7, up:80, down:75, ascent:380},
    stamps:[{name:"Skrzynka przy wieży widokowej",type:"📬",note:"U dołu wieży na szczycie"}],
    photo:"Przy wieży widokowej (drewniana, 25.5m, z 2021 r.) lub przy obelisku na szczycie (strona czeska)" },
  { id:22, name:"Rudawiec", height:1106, range:"Góry Bialskie", difficulty:2, lat:50.244845, lon:16.976359, season:[5,6,7,8,9,10], terrain:"forest",
    parking:[{name:"Bielice",lat:50.2583,lon:16.9917,note:"~20 miejsc, darmowy, szuter. Przy leśniczówce, dobry start na Rudawiec"}],
    station:{name:"Stronie Śląskie PKP", info:"Bus do Bielic ~30 min"},
    trail:{dist:8, up:90, down:85, ascent:460},
    stamps:[{name:"Chata Cyborga Bielice",type:"🏡",note:"W wiosce start"},{name:"Pieczątka na szczycie",type:"📬",note:"Skrzynka przy tablicy"}],
    photo:"Na szczycie z widokiem na Masyw Śnieżnika" },
  { id:23, name:"Kowadło", height:989, range:"Góry Złote", difficulty:2, lat:50.263867, lon:17.013299, season:[5,6,7,8,9,10], terrain:"forest",
    parking:[{name:"Bielice",lat:50.2583,lon:16.9917,note:"~20 miejsc, darmowy, szuter. Przy leśniczówce, można połączyć z Rudawcem"}],
    station:{name:"Stronie Śląskie PKP", info:"Bus do Bielic"},
    trail:{dist:9, up:100, down:95, ascent:490},
    stamps:[{name:"Pieczątka na szczycie",type:"📬",note:"Skrzynka na Kowadle"}],
    photo:"Przy tablicy szczytowej z widokiem na Masyw Śnieżnika" },
  { id:24, name:"Ślęża", height:718, range:"Masyw Ślęży", difficulty:1, lat:50.864087, lon:16.707496, season:[3,4,5,6,7,8,9,10,11,12], terrain:"forest",
    parking:[{name:"Sobótka - Parking pod Wieżycą",lat:50.8916878,lon:16.7381215,note:"~250 miejsc, 15 zł/dzień, utwardzony. Szlaki: żółty przez Przełęcz pod Wieżycą lub czerwony"},{name:"Przełęcz Tąpadła",lat:50.8450639,lon:16.6974378,note:"~80 miejsc, 20 zł/dzień, płatny. Szlak żółty (najprostszy) lub niebieski (urokliwy, trudniejszy)"}],
    station:{name:"Sobótka PKP", info:"Szlak ze stacji ~1.5h"},
    trail:{dist:7, up:75, down:70, ascent:380},
    stamps:[{name:"Dom Turysty PTTK Góra Ślęża",type:"🏠",note:"Skrzynka przy wejściu do schroniska i wewnątrz przy kasie"}],
    photo:"Przy tabliczce z wysokością 718 m n.p.m. przy schodach/bramie kościoła NMP" },
  { id:25, name:"Biskupia Kopa", height:889, range:"Góry Opawskie", difficulty:2, lat:50.256933, lon:17.428860, season:[4,5,6,7,8,9,10,11], terrain:"forest",
    parking:[{name:"Park Rosenau Pokrzywna",lat:50.2703,lon:17.4250,note:"~100 miejsc, 10-15 zł/dzień, asfalt. Najlepszy dostęp do szlaku"}],
    station:{name:"Głuchołazy PKP", info:"Bus do Pokrzywnej ~30 min"},
    trail:{dist:7, up:80, down:75, ascent:420},
    stamps:[{name:"Skrzynka na szczycie",type:"📬",note:"Przy wieży/wiacie, od 2025"},{name:"Górski Dom Turysty pod Biskupią Kopą",type:"🏠",note:"Schronisko poniżej szczytu, 2 pieczątki"}],
    photo:"Na wieży widokowej z widokiem na trzy kraje: PL/CZ/SK" },
  { id:26, name:"Łysica", height:614, range:"Góry Świętokrzyskie", difficulty:1, lat:50.891616, lon:20.896598, season:[3,4,5,6,7,8,9,10,11,12], terrain:"forest",
    parking:[{name:"Święta Katarzyna",lat:50.9010232,lon:20.8809690,note:"~50 miejsc, darmowy, asfalt. Przy wejściu do ŚPN"}],
    station:{name:"Kielce PKP", info:"Bus do Św. Katarzyny ~1h"},
    trail:{dist:5, up:45, down:40, ascent:260},
    stamps:[{name:"Pieczątka na szczycie",type:"📬",note:"Skrzynka od 31.10.2025"},{name:"Ośrodek Jodełka Św. Katarzyna",type:"🏠",note:"Przy parkingu"}],
    photo:"Przy drewnianej tablicy wśród gołoborza jodłowego" },
  { id:27, name:"Czupel", height:931, range:"Beskid Mały", difficulty:2, lat:49.7678808, lon:19.1610286, season:[4,5,6,7,8,9,10,11], terrain:"forest",
    parking:[{name:"Kobiernice",lat:49.7825,lon:19.1683,note:"~20 miejsc, darmowy, szuter. Przy starcie szlaku"}],
    station:{name:"Bielsko-Biała PKP", info:"Bus do Kobiernic ~30 min"},
    trail:{dist:7, up:80, down:75, ascent:430},
    stamps:[{name:"Pieczątka na szczycie",type:"📬",note:"Skrzynka przy tablicy"}],
    photo:"Na szczycie wśród lasu - tablica i skrzynka" },
  { id:28, name:"Lubomir", height:904, range:"Beskid Makowski", difficulty:2, lat:49.766880, lon:20.059672, season:[4,5,6,7,8,9,10,11], terrain:"forest",
    parking:[{name:"Węglówka - Gościniec pod Lubomirem",lat:49.7750,lon:20.0550,note:"~30 miejsc, darmowy, szuter. Dobry punkt startowy na Lubomir"}],
    station:{name:"Myślenice PKP", info:"Bus do Węglówki ~30 min"},
    trail:{dist:5, up:55, down:50, ascent:310},
    stamps:[{name:"Gościniec pod Lubomirem",type:"🏡",note:"Przy parkingu"},{name:"Obserwatorium Astronomiczne",type:"🔭",note:"Na szczycie, pieczątka dostępna"}],
    photo:"Na szczycie przy tablicy - 40 min od parkingu" }
];

// ============================================================
// API KEYS
// ============================================================
const SUPABASE_URL = 'https://bocwhfubyuwpsdcvqiqb.supabase.co';
const SUPABASE_KEY = 'sb_publishable__szHGpjSyOWzCDXQMSD6eA_TKu8ClW0';
const MAPY_API_KEY = 'BObGLXgTLrca8IyrEW2Lw-3F4VfKzMAmO2KMjqLanFU';
// Gemini API key zarządzany przez ai.js (pobierany z Supabase)

// Nazwy szczytów do generowania kodów sync
const PEAK_NAMES_FOR_CODE = [
  'rysy','babia','sniezka','snieznik','tarnica','turbacz','radziejowa',
  'skrzyczne','mogielica','lackowa','wysoka','szczeliniec','kopa','skopiec',
  'skalnik','chelmiec','waligora','sowa','klodzka','jagodna','orlica',
  'rudawiec','kowadlo','sleza','biskupia','lysica','czupel','lubomir'
];
